### ISSUE TITLE
Sync Calendar upon Refresh

### ISSUE THREAD

**Issue by drparcon** [CMSC-129C-Projects/CalPal#44]
Currently the calendars only sync upon adding. We should make it so that calendars sync on refresh to add any new events in the shared calendar as cards.

**Comment by grantyap** [comment]
One thing that also happens is that when CalPal tries to sync events, it also tries to create cards for events that have already been deleted. To fix this, we should keep track of which cards were deleted. When we sync new events, we check whether they're part of this array of previously deleted cards before creating a new one.

**Comment by BigBlackLab19** [comment]
Looking at the current fix of this issue - everything seems to work fine. However, regarding Grant's previous comment - any card that is not found in the user's data will still be synced. This is not a big issue, since we expect users to archive and delete cards only after the event is finished. This would mean that if that is the case, the card would not sync since our implementation does not sync cards before the current date.
